### ISSUE TITLE
Not all colors inclus

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#14]
Not all colors that can be used for wool, stained glass and stained clay are given the correct color

From aliases-english.sk:
![image](https://cloud.githubusercontent.com/assets/1556738/13793662/4a3bc5da-eaf8-11e5-89c7-bf8de005cf6c.png)

**Comment by elgbar** [comment]
Language Version: 1.9.0
(ThemesName) Version: 2.1.1

**Comment by tim740** [comment]
Dark Green works just doesn't show for [dark] green (thats normal)
Light gray/gray is colored right (it's hard to see)

Fixed in v1.9.1 (only pink and brown are missing, they show as the wrong colors anyway)

**Comment by elgbar** [comment]
I believe you forgot some colors:
orange should be same color as gold (&6)
![image](https://cloud.githubusercontent.com/assets/1556738/13893466/e151281c-ed5e-11e5-948e-75b94cb59005.png)
lime same color as light green (&a)
![image](https://cloud.githubusercontent.com/assets/1556738/13893479/01df216a-ed5f-11e5-886b-6d4841fc1ab4.png)
cyan same color as aqua (&3)
![image](https://cloud.githubusercontent.com/assets/1556738/13893462/d46c541e-ed5e-11e5-89a2-307aad1df60d.png)
magenta same color as light purple (&d)
![image](https://cloud.githubusercontent.com/assets/1556738/13893515/37bdb5da-ed5f-11e5-9fb0-ed53e0fcfb97.png)

And I agree that pink and brown show up as different colors so you don't need to add them :P
![image](https://cloud.githubusercontent.com/assets/1556738/13893543/7509778a-ed5f-11e5-9e39-3e5a9ef483c3.png)

**Comment by elgbar** [comment]
On another note:
If possible can you make colors with the prefix light have the same color as the color?
